-- Create table scripts
DROP TABLE IF EXISTS ADDRESS;
DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE EMPLOYEE(
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  date_of_birth VARCHAR(250) NOT NULL
);


CREATE TABLE ADDRESS(
  emp_id INT NOT NULL,
  line1 VARCHAR(250) NOT NULL,
  line2 VARCHAR(250) DEFAULT NULL,
  city  VARCHAR(250) NOT NULL,
  state VARCHAR(250) NOT NULL,
  country VARCHAR(250) NOT NULL,
  zip_code VARCHAR(250) NOT NULL,
  foreign key (emp_id) references EMPLOYEE(id)
);